export {default as Header } from './Header';
export {default as MainSlide } from './MainSlide';
export {default as Footer } from './Footer';
export {default as TypeCheckForm} from './forms/TypeCheckForm';
export {default as GridCard } from './GridCard';
export {default as StrongPoint } from './StrongPoint';
export {default as Py } from './forms/Py';
export {default as Region } from './forms/Region';
export {default as Schedule } from './forms/Schedule';
export {default as Contact } from './forms/Contact';
export {default as CallTime } from './forms/CallTime';
export {default as Agree } from './forms/Agree';
export {default as Qna } from './forms/Qna';
export {default as Request } from './forms/Request';
export {default as EstimateForm } from './forms/EstimateForm';
export {default as ConsultProcess } from './forms/ConsultProcess';
